version: '3.8'

services:
    backend:
        build:
            context: ./backend
            args:
                MODE: ${MODE}
        env_file:
            - .env

    postgres:
        env_file:
            - .env
