version: '3.8'

services:
    backend:
        build:
            context: ./backend
            args:
                MODE: ${MODE}
        ports:
            - '${BACKEND_PORT}:${BACKEND_PORT}'
        env_file:
            - .env
        networks:
            - app-network

    frontend:
        build:
            context: ./frontend
        ports:
            - '${FRONTEND_PORT}:80'
        environment:
            BACKEND_PORT: ${BACKEND_PORT}
        networks:
            - app-network

    postgres:
        image: postgres:13
        env_file:
            - .env
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_NAME}
        ports:
            - '${DB_PORT}:${DB_PORT}'
        volumes:
            - pgdata:/var/lib/postgresql/data
        networks:
            - app-network

volumes:
    pgdata:

networks:
    app-network:
