apiVersion: apps/v1
kind: Deployment
metadata:
    name: frontend-deploy
    namespace: todo-app-deploy
spec:
    replicas: 1
    selector:
        matchLabels:
            app: frontend
    template:
        metadata:
            labels:
                app: frontend
        spec:
            containers:
                - name: frontend
                  image: ivladii/todo-frontend-dev:latest
                  ports:
                      - containerPort: 80
                  envFrom:
                      - configMapRef:
                            name: app-config
