apiVersion: apps/v1
kind: Deployment
metadata:
    name: postgres-deploy
    namespace: todo-app-deploy
spec:
    replicas: 1
    selector:
        matchLabels:
            app: postgres
    template:
        metadata:
            labels:
                app: postgres
        spec:
            containers:
                - name: postgres
                  image: postgres:13
                  ports:
                      - containerPort: 5432
                  env:
                      - name: POSTGRES_USER
                        valueFrom:
                            secretKeyRef:
                                name: app-secrets
                                key: DB_USER
                      - name: POSTGRES_PASSWORD
                        valueFrom:
                            secretKeyRef:
                                name: app-secrets
                                key: DB_PASSWORD
                      - name: POSTGRES_DB
                        valueFrom:
                            secretKeyRef:
                                name: app-secrets
                                key: DB_NAME
                  volumeMounts:
                      - name: postgres-data
                        mountPath: /var/lib/postgresql/data
            volumes:
                - name: postgres-data
                  emptyDir: {}
