name: CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        services:
            postgres:
                image: postgres:13
                env:
                    POSTGRES_USER: todo-test
                    POSTGRES_PASSWORD: todo-test
                    POSTGRES_DB: todo-test
                options: >-
                    --health-cmd pg_isready
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5
                ports:
                    - 5432:5432

        steps:
            - uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: '18'

            - name: Install dependencies and run tests for backend
              working-directory: ./backend
              run: |
                  npm install
                  npm test

#      - name: Install dependencies and run build for frontend
#        working-directory: ./frontend
#        run: |
#          npm install
#          npm run build
