name: Build and Push Docker Images

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Print environment variable
        run: echo "My variable value is ${{ vars.MODE }}"
      - name: Build and push backend image
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            MODE=${{ vars.MODE }}
          tags: |
            ivladii/todo-backend-dev:latest
            ivladii/todo-backend-dev:${{ github.sha }}

      - name: Build and push frontend image
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ivladii/todo-frontend-dev:latest
            ivladii/todo-frontend-dev:${{ github.sha }}

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3

      - name: Configure kubectl
        run: |
          echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > kubeconfig
          export KUBECONFIG=./kubeconfig

      - name: Update deployment manifests
        run: |
          sed -i "s|ivladii/todo-backend-dev:.*|ivladii/todo-backend-dev:${{ github.sha }}|g" k8s/*.yaml
          sed -i "s|ivladii/todo-frontend-dev:.*|ivladii/todo-frontend-dev:${{ github.sha }}|g" k8s/*.yaml

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/

      - name: Verify deployment
        run: |
          kubectl rollout status deployment/todo-backend
          kubectl rollout status deployment/todo-frontend
